# Generated by Django 4.2.1 on 2023-05-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardskillsmodel',
            options={'verbose_name': 'Навичка', 'verbose_name_plural': 'Навички'},
        ),
        migrations.AlterModelOptions(
            name='languagesmodel',
            options={'verbose_name': 'Мова програмування', 'verbose_name_plural': 'Мови програмування'},
        ),
        migrations.AlterModelOptions(
            name='projectsmodel',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекти'},
        ),
        migrations.AlterModelOptions(
            name='useraccountmodel',
            options={'verbose_name': 'Обліковий запис користувача', 'verbose_name_plural': 'Облікові записи користувачів'},
        ),
        migrations.AlterModelTable(
            name='hardskillsmodel',
            table='hard_skills',
        ),
        migrations.AlterModelTable(
            name='languagesmodel',
            table='languages',
        ),
        migrations.AlterModelTable(
            name='projectsmodel',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='useraccountmodel',
            table='user_account',
        ),
    ]
