# Generated by Django 4.2.1 on 2023-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_hardskillsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmodel',
            name='projects',
            field=models.ManyToManyField(blank=True, to='account.projectsmodel'),
        ),
    ]
