# Generated by Django 4.2.1 on 2023-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccountmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='account.useraccountmodel'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='type_project',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
