# Generated by Django 4.2.1 on 2023-05-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_projectsmodel_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='avatar',
            field=models.ImageField(blank=True, default='https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp', null=True, upload_to='avatars/'),
        ),
    ]
